apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: airis
  namespace: default
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16.11

  superuserSecret:
    name: airis-superuser

  bootstrap:
    initdb:
      database: airis
      owner: airis
      secret:
        name: airis-app-user

  storage:
    size: 5Gi

  resources:
    requests:
      cpu: "500m"
      memory: "0.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
      wal_level: "replica"
      log_min_duration_statement: "500"